chore: Improve build local script
bonitasoft-labs/appsmith pull request #3
Opened 2024-03-27 10:17 UTC by benjaminParisel

* waiting for thread ending before build docker image
* rename docker image name

2024-03-27 15:13 UTC, csouchet approved these changes

2024-03-28 11:00 UTC, jeromecambon reviewed
On a freshly cloned repo, I get the following error:
 ```
=> CACHED [2/8] RUN mkdir -p ./editor ./rts ./backend/plugins                                                     0.0s
 => CACHED [3/8] COPY deploy/docker/fs /                                                                           0.0s
 => CACHED [4/8] COPY ./app/server/dist/server-*.jar backend/server.jar                                            0.0s
 => CACHED [5/8] COPY ./app/server/dist/plugins/*.jar backend/plugins/                                             0.0s
 => CACHED [6/8] COPY ./app/client/build editor/                                                                   0.0s
 => ERROR [7/8] COPY ./app/client/packages/rts/dist rts/                                                           0.0s
------
 > [7/8] COPY ./app/client/packages/rts/dist rts/:
------
Dockerfile:26
--------------------
  24 |     
  25 |     # Add RTS - Application Layer
  26 | >>> COPY ./app/client/packages/rts/dist rts/
  27 |     
  28 |     ENV PATH /opt/appsmith/utils/node_modules/.bin:/opt/java/bin:/opt/node/bin:$PATH
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ca202cce-47ea-4fcc-ad33-d7130584f5a2::qgcbmczbzlkvipxxroq0t3hx6: "/app/client/packages/rts/dist": not found

```

Seems the rts package is not built...

2024-03-28 16:00 UTC, jeromecambon approved these changes
Works fine now for me!
Just a small comment: I would not handle script time, which is not very useful since:
- this is already provided with the 'time' command (`$ time build_local.sh`)
- Time in seconds is not very helpful

2024-03-29 11:16 UTC, csouchet requested changes
I have the following error with the last changes 😢

```
+ yarn build
dd510d5
Sentry Auth Token: 
Building for non-airgapped Appsmith instances
node:internal/modules/cjs/loader:1137
 throw err;
 ^
Error: Cannot find module '/Users/csouchet/Source/Bonita/UID/appsmith/app/client/node_modules/@craco/craco/dist/bin/craco.js'
   at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
   at Module._load (node:internal/modules/cjs/loader:975:27)
   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
   at node:internal/main/run_main_module:28:49 {
 code: 'MODULE_NOT_FOUND',
 requireStack: []
}
Node.js v18.19.1
```

2024-03-29 13:42 UTC, csouchet approved these changes

2024-03-29 15:21 UTC, merged